---
title: Intro to Python
author: Cara Johnston
date: '2020-05-14'
slug: intro-to-python
categories: []
tags: []
description: ''
---
##Python Basics

Python was pretty challenging for me to learn at first, so here are some basics that should help other python learners! 

One of the coolest parts about using Python in RStudio is combining the two together. This allows you to combine objects from both Python and R, which can let you write fun sentences.

```{r}

library(reticulate)
wow<-"python can be"

```

```{python}
surprise ="really fun"
print(r.wow,surprise)

```

Another thing that is unique about Python (and kinda cool!) is indexing. To try this out, first we have to create a list:

```{python}
list=["apple", "orange", "banana", "cherry"]
```

Once you have a list created, you can start indexing. Note: in python, indexing begins at position "0", instead of "1". In this case, the object in position 1 is "orange", not "apple". 

```{python}
list[1]
```

Indexing can also be used to grab a portion of the list. To get the middle two objects from the list, we can use the following code:

```{python}
list[1:3]
```

One last trick!

Indexing can also be used to grab every other object from a list:
```{python}
list[::2]
```

I still have a lot to learn, but I'm grateful for the few commands I have learned. Hopefully I will have more tricks to share in the future!